[variables]
main_domain = "${domain}"
session_secret = "${password:32}"

[config]
[[config.domains]]
serviceName = "silex"
port = 6805
host = "${main_domain}"

[config.env]
SILEX_URL = "http://${main_domain}"
SILEX_SESSION_SECRET = "${session_secret}"
