# If you are on a machine with ARM architecture, please add a "-arm" suffix to the calcom image on line 19.
# For example, `calcom/cal.com:v6.2.0` will become `calcom/cal.com:v6.2.0-arm`

# If serving the instance on https, change `NEXT_PUBLIC_WEBAPP_URL` (Line 28) and `NEXTAUTH_URL` (Line 30) to https

services:
  postgres:
    image: postgres:16-alpine

    volumes:
      - calcom-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - DATABASE_URL=postgres://postgres:password@postgres:5432/db

  calcom:
    image: calcom/cal.com:v6.2.0
    depends_on:
      - postgres
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - CALENDSO_ENCRYPTION_KEY=${CALENDSO_ENCRYPTION_KEY}
      - DATABASE_URL=postgres://postgres:password@postgres:5432/db
      - DATABASE_DIRECT_URL=postgres://postgres:password@postgres:5432/db
      - DATABASE_HOST=postgres:5432
      - NEXT_PUBLIC_WEBAPP_URL=http://${CALCOM_HOST}
      - ALLOWED_HOSTNAMES="${CALCOM_HOST}"
      - NEXTAUTH_URL=http://${CALCOM_HOST}/api/auth
      - NEXT_PUBLIC_DISABLE_SIGNUP=${DISABLE_SIGNUP}
      - EMAIL_SERVER_HOST=${SMTP_SERVER}
      - EMAIL_SERVER_PORT=${SMTP_PORT}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}


volumes:
  calcom-data:
