[variables]
main_domain = "${domain}"
admin_password = "${password:32}"
postgres_password = "${password:32}"

[config]
env = [
  "WEBLATE_SITE_DOMAIN=${main_domain}",
  "WEBLATE_SITE_TITLE=Weblate",
  "WEBLATE_ADMIN_NAME=Weblate Admin",
  "WEBLATE_ADMIN_EMAIL=admin@${main_domain}",
  "WEBLATE_ADMIN_PASSWORD=${admin_password}",
  "WEBLATE_SERVER_EMAIL=weblate@${main_domain}",
  "WEBLATE_DEFAULT_FROM_EMAIL=weblate@${main_domain}",
  "WEBLATE_ENABLE_HTTPS=0",
  "WEBLATE_REGISTRATION_OPEN=1",
  "POSTGRES_USER=weblate",
  "POSTGRES_PASSWORD=${postgres_password}",
  "POSTGRES_DB=weblate",
]
mounts = []

[[config.domains]]
serviceName = "weblate"
port = 8080
host = "${main_domain}"
