[variables]
main_domain = "${domain}"
jwt_secret = "${password:64}"
cloud_token = "${password:48}"
admin_token = "${password:48}"

[config]
env = [
  "ENGRAM_JWT_SECRET=${jwt_secret}",
  "ENGRAM_CLOUD_TOKEN=${cloud_token}",
  "ENGRAM_CLOUD_ADMIN=${admin_token}",
  "ENGRAM_CLOUD_ALLOWED_PROJECTS=*",
]
mounts = []

[[config.domains]]
serviceName = "engram"
port = 8080
host = "${main_domain}"
path = "/dashboard"
