[variables]
main_domain = "${domain}"
app_url = "http://${main_domain}"
app_secret = "${hash:64}"
instance_id = "${hash:32}"
database_name = "shopware"
database_user = "shopware"
database_password = "${hash:32}"
mysql_root_password = "${hash:32}"
redis_password = "${hash:32}"
database_url = "mysql://${database_user}:${database_password}@database:3306/${database_name}?charset=utf8mb4"
lock_dsn = "redis://:${redis_password}@redis:6379/1"
php_session_save_path = "tcp://redis:6379?auth=${redis_password}"
install_admin_username = "admin"
install_admin_password = "${password:20}"
shopware_version = "6.7.12.1"
shopware_docker_version = "0.3.0"
shopware_cli_image = "shopware/shopware-cli:0.14.3-php-8.4"
shopware_base_image = "shopware/docker-base:8.4.19-nginx"
enable_demo_data = "1"
demo_data_version = "2.1.0"

[config]

[[config.domains]]
serviceName = "shopware"
port = 8000
host = "${main_domain}"

[config.env]
APP_ENV = "prod"
APP_URL = "${app_url}"
APP_SECRET = "${app_secret}"
INSTANCE_ID = "${instance_id}"
SHOPWARE_VERSION = "${shopware_version}"
SHOPWARE_DOCKER_VERSION = "${shopware_docker_version}"
SHOPWARE_CLI_IMAGE = "${shopware_cli_image}"
SHOPWARE_BASE_IMAGE = "${shopware_base_image}"
ENABLE_DEMO_DATA = "${enable_demo_data}"
DEMO_DATA_VERSION = "${demo_data_version}"
DATABASE_HOST = "database"
DATABASE_PORT = "3306"
DATABASE_NAME = "${database_name}"
DATABASE_USER = "${database_user}"
DATABASE_PASSWORD = "${database_password}"
DATABASE_URL = "${database_url}"
MYSQL_ROOT_PASSWORD = "${mysql_root_password}"
REDIS_HOST = "redis"
REDIS_PORT = "6379"
REDIS_PASSWORD = "${redis_password}"
MAILER_DSN = "null://localhost"
LOCK_DSN = "${lock_dsn}"
TRUSTED_PROXIES = "private_ranges"
SYMFONY_TRUSTED_PROXIES = "private_ranges"
SYMFONY_TRUSTED_HEADERS = "x-forwarded-for,x-forwarded-host,x-forwarded-proto,x-forwarded-port,x-forwarded-prefix"
COMPOSER_PLUGIN_LOADER = "1"
SHOPWARE_HTTP_CACHE_ENABLED = "1"
SHOPWARE_HTTP_DEFAULT_TTL = "7200"
INSTALL_LOCALE = "en-GB"
INSTALL_CURRENCY = "EUR"
INSTALL_ADMIN_USERNAME = "${install_admin_username}"
INSTALL_ADMIN_PASSWORD = "${install_admin_password}"
PHP_SESSION_HANDLER = "redis"
PHP_SESSION_SAVE_PATH = "${php_session_save_path}"
PHP_SESSION_COOKIE_LIFETIME = "0"
PHP_SESSION_GC_MAXLIFETIME = "1440"
PHP_MAX_UPLOAD_SIZE = "128M"
PHP_MAX_EXECUTION_TIME = "300"
PHP_MEMORY_LIMIT = "512M"
FPM_PM = "dynamic"
FPM_PM_MAX_CHILDREN = "20"
FPM_PM_START_SERVERS = "4"
FPM_PM_MIN_SPARE_SERVERS = "2"
FPM_PM_MAX_SPARE_SERVERS = "6"
MESSENGER_TRANSPORT_DSN = "doctrine://default?queue_name=async"
MESSENGER_TRANSPORT_LOW_PRIORITY_DSN = "doctrine://default?queue_name=low_priority"
MESSENGER_TRANSPORT_FAILURE_DSN = "doctrine://default?queue_name=failed"
BLUE_GREEN_DEPLOYMENT = "0"
