[variables]
main_domain = "${domain}"
admin_password = "${password:32}"

[config]
env = [
  "ACCEPT_EULA=Y",
  "SEQ_API_CANONICALURI=https://${main_domain}",
  "SEQ_FIRSTRUN_ADMINPASSWORD=${admin_password}"
]
mounts = []

[[config.domains]]
serviceName = "seq"
port = 80
host = "${main_domain}"