version: "3.8"

services:
  verdaccio:
    image: verdaccio/verdaccio:6
    environment:
      - VERDACCIO_PORT=4873
    expose:
      - 4873
    volumes:
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_plugins:/verdaccio/plugins
      - ../files/conf:/verdaccio/conf

volumes:
  verdaccio_storage:
  verdaccio_plugins:
