[variables]
main_domain = "${domain}"

[config]
mounts = []
[[config.domains]]
serviceName = "cookiecloud"
port = 8088
host = "${main_domain}"

[config.env]
# No environment variables required by default
