[variables]
MYSQL_ROOT_PASSWORD = "${password:32}"
MATOMO_DATABASE_DB = "matomo"
MATOMO_DATABASE_USER = "matomo"
MATOMO_DATABASE_PASSWORD = "${password:32}"
MATOMO_DATABASE_HOST = "db"

[config]
[[config.domains]]
serviceName = "matomo"
port = 80
host = "${domain}"

[config.env]
MATOMO_DATABASE_DB = "${MATOMO_DATABASE_DB}"
MATOMO_DATABASE_USER = "${MATOMO_DATABASE_USER}"
MATOMO_DATABASE_PASSWORD = "${MATOMO_DATABASE_PASSWORD}"
MATOMO_DATABASE_HOST = "${MATOMO_DATABASE_HOST}"
MYSQL_ROOT_PASSWORD = "${MYSQL_ROOT_PASSWORD}"
MYSQL_PASSWORD = "${MATOMO_DATABASE_PASSWORD}"
MYSQL_DATABASE = "${MATOMO_DATABASE_DB}"
MYSQL_USER = "${MATOMO_DATABASE_USER}"
