[variables]
main_domain = "${domain}"

[config]
env = [
    "USER_UID=1000",
    "USER_GID=1000",
    "FORGEJO_DOMAIN=${main_domain}",
    "FORGEJO_SSH_DOMAIN=${main_domain}"
]
mounts = []

[[config.domains]]
serviceName = "forgejo"
port = 3_000
host = "${main_domain}"
