version: "3.8"

services:
  naviserver:
    image: ghcr.io/andre-carbajal/naviserver:2.4.5
    restart: unless-stopped
    expose:
      - "23008"
    ports:
      - "25565-25600"
    environment:
      NAVISERVER_HOST: ${NAVISERVER_HOST}
      NAVISERVER_PORT: ${NAVISERVER_PORT}
      NAVISERVER_ALLOWED_ORIGINS: ${NAVISERVER_ALLOWED_ORIGINS}
      NAVISERVER_SECRET_KEY: ${NAVISERVER_SECRET_KEY}
      NAVISERVER_CLI_TOKEN: ${NAVISERVER_CLI_TOKEN}
      CURSEFORGE_API_KEY: ${CURSEFORGE_API_KEY}
    volumes:
      - naviserver-data:/data
volumes:
  naviserver-data: {}
