[variables]
timezone = "Etc/UTC"
api_key_pepper = "${password:64}"

[config]
[[config.domains]]
serviceName = "homebox"
port = 7745
host = "${domain}"

[config.env]
TZ = "${timezone}"
HBOX_AUTH_API_KEY_PEPPER = "${api_key_pepper}"
