version: "3.8"
services:
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.108.1
    restart: unless-stopped
    expose:
      - 8428
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=${RETENTION_PERIOD}"
      - "--httpListenAddr=:8428"
    volumes:
      - vm-data:/storage

volumes:
  vm-data: {}
