services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      APP_KEY: ${APP_KEY}
      DB_CONNECTION: sqlite
    volumes:
      - speedtest_config:/config
    expose:
      - "80"
volumes:
  speedtest_config:
