[variables]
main_domain = "${domain}"
app_key = "${base64:32}"

[config]
mounts = []

[[config.domains]]
serviceName = "speedtest-tracker"
port = 80
host = "${main_domain}"

[config.env]
APP_KEY = "base64:${app_key}"
PUID = "1000"
PGID = "1000"
