[variables]
main_domain = "${domain}"

[config]
[[config.domains]]
serviceName = "omniroute"
port = 20128
host = "${main_domain}"

[config.env]
JWT_SECRET = "${base64:64}"
API_KEY_SECRET = "${base64:64}"
INITIAL_PASSWORD = "${base64:64}"
STORAGE_ENCRYPTION_KEY = "${base64:64}"
STORAGE_ENCRYPTION_KEY_VERSION = "v1"
DISABLE_SQLITE_AUTO_BACKUP = false
PORT = 20128
API_PORT = 20129
OMNIROUTE_USE_TURBOPACK = 1
NODE_ENV = "production"
MACHINE_ID_SALT = "endpoint-proxy-salt"
AUTH_COOKIE_SECURE = false
REQUIRE_API_KEY = false
ALLOW_API_KEY_REVEAL = false
BASE_URL = "http://localhost:20128"
CLOUD_URL = ""
NEXT_PUBLIC_BASE_URL = "http://localhost:20128"
ENABLE_SOCKS5_PROXY = true
NEXT_PUBLIC_ENABLE_SOCKS5_PROXY = true
PROVIDER_LIMITS_SYNC_INTERVAL_MINUTES = 70
APP_LOG_TO_FILE = true
