services:
  jellyseerr:
    image: fallenbagel/jellyseerr:2.7.3
    restart: unless-stopped
    volumes:
      - jellyseerr_config:/app/config
    environment:
      LOG_LEVEL: info
    expose:
      - "5055"
volumes:
  jellyseerr_config:
