version: "3.8"
services:
  keydb:
    image: eqalpha/keydb:latest
    restart: unless-stopped
    command: keydb-server /etc/keydb/keydb.conf --server-threads 2 --requirepass ${KEYDB_PASSWORD}
    volumes:
      - keydb-data:/data

volumes:
  keydb-data: {}
