services:
  sftpgo:
    image: drakkan/sftpgo:v2.7.3
    restart: unless-stopped
    volumes:
      - sftpgo_data:/srv/sftpgo
      - sftpgo_home:/var/lib/sftpgo
    expose:
      - "8080"
      - "2022"
volumes:
  sftpgo_data:
  sftpgo_home:
