services:
  filegator:
    image: filegator/filegator:v7.14.3
    restart: unless-stopped
    volumes:
      - filegator_repository:/var/www/filegator/repository
      - filegator_private:/var/www/filegator/private
    expose:
      - "8080"
volumes:
  filegator_repository:
  filegator_private:
